name: dart_pen
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.3
description: >
  Drawing a path of segments, each having one or more lines.
  A segment is drawn based on the input from a user.
  The input consists of rotate, advance and iterate values.
dependencies:
  browser: any
